baseurl = "http://naoatsu.github.io/prose/"
languageCode = "en-us"
title = "prose"
theme = "hugo-cactus-theme"
googleAnalytics = "UA-74075697-1"
disqusShortname = "nodico"
author = "Noat"
publishdir = "public"

[permalinks]
  post = "/:year/:month/:day/:filename/"

[params]
        name = "Noat"
        description = "技術&読書メモ"
        bio = "Programmer - PT"
        twitter = "Noat11111111"
        enableRSS = true
        home = "Home"
        about = "About"
        contact = "Contact"
        subscribe = "feed"
        copyright = "written by noat11111111"
        aboutAuthor = "PT^Programmer^PartWorker"

    socialIconStyle = "circle"

[social]
    facebook  = "https://www.facebook.com/naoatsu.kurata.7"
    github    = "https://github.com/naoatsu/"
    twitter   = "https://twitter.com/Noat11111111"
